/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import expoNotifications from "@surunnuage/strapi-plugin-expo-notifications/strapi-admin";
import firebaseAuth from "@swensonhe/strapi-plugin-firebase-auth/strapi-admin";
import strapiPluginFcm from "strapi-plugin-fcm/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    documentation: documentation,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "expo-notifications": expoNotifications,
    "firebase-auth": firebaseAuth,
    "strapi-plugin-fcm": strapiPluginFcm,
  },
});
